### ISSUE TITLE
Indexing failure: latest Serilog dev package (3.0.0)

### ISSUE THREAD

**Issue by daningalla** [verticalsoftware/vertical-pipelines#17]
```
tripleslash-services-indexer-1        | fail: Tripleslash.ApiServices.IndexingService.IndexingHandler[0]
tripleslash-services-indexer-1        |       Build failed, ecosystem: .net, packageId: Serilog, version: 3.0.0-dev-01691
tripleslash-services-indexer-1        |       Tripleslash.Services.ServiceException: Indexing of 'Serilog-3.0.0-dev-01691' failed due to an unrecoverable error.
tripleslash-services-indexer-1        |        ---> System.InvalidOperationException: Cannot resolved documentation for module System.Runtime
tripleslash-services-indexer-1        |          at Tripleslash.BuildServices.DotNet.XmlDoc.DocumentationIndex.TryGetFrameworkReferenceContentAsync(IBuildContext context, String assemblyName, Boolean require, CancellationToken cancellationToken)
tripleslash-services-indexer-1        |          at Tripleslash.BuildServices.DotNet.XmlDoc.DocumentationIndex.GetCacheEntriesAsync(IBuildContext context, IModule module, CancellationToken cancellationToken)
tripleslash-services-indexer-1        |          at Tripleslash.BuildServices.DotNet.XmlDoc.DocumentationIndex.GetAssemblyDocIndexAsync(IBuildContext context, IModule module, String dependencyGroupId, CancellationToken cancellationToken)
tripleslash-services-indexer-1        |          at Tripleslash.BuildServices.DotNet.XmlDoc.AssemblyDocIndexBuilder.GetMemberDocFromReferenceModuleIndexAsync(IBuildContext context, IModule module, String memberIdS
```

**Comment by daningalla** [comment]
Wrong project...
